In [59]:
import pandas as pd
import  numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model  import LinearRegression 

In [60]:
df=pd.read_csv("C:/Users/BENJAMIN/Downloads/insurance.csv")

In [61]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       1338 non-null   int64  
 1   sex       1338 non-null   object 
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64  
 4   smoker    1338 non-null   object 
 5   region    1338 non-null   object 
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB


In [62]:
df.head()

age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [63]:
columns=df.columns.values.tolist()
print(columns)

['age', 'sex', 'bmi', 'children', 'smoker', 'region', 'charges']


In [64]:
# Check for missing data
df.isnull().sum()

# Impute missing data with mean
df = df.fillna(df.mean())
print (df)

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]


C:\Users\BENJAMIN\AppData\Local\Temp\ipykernel_6076\883001002.py:5: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df = df.fillna(df.mean())


In [65]:
from sklearn.preprocessing import LabelEncoder
cat_cols = ["sex", "smoker", "region"]
# Create LabelEncoder object
le = LabelEncoder()
# Encode the categorical features
for col in cat_cols:
    df[col] = le.fit_transform(df[col])
# Print the encoded dataset
print(df)

      age  sex     bmi  children  smoker  region      charges
0      19    0  27.900         0       1       3  16884.92400
1      18    1  33.770         1       0       2   1725.55230
2      28    1  33.000         3       0       2   4449.46200
3      33    1  22.705         0       0       1  21984.47061
4      32    1  28.880         0       0       1   3866.85520
...   ...  ...     ...       ...     ...     ...          ...
1333   50    1  30.970         3       0       1  10600.54830
1334   18    0  31.920         0       0       0   2205.98080
1335   18    0  36.850         0       0       2   1629.83350
1336   21    0  25.800         0       0       3   2007.94500
1337   61    0  29.070         0       1       1  29141.36030

[1338 rows x 7 columns]


In [66]:
# Separate features and target
X = df.drop(['charges'], axis=1)
y = df['charges']

In [67]:
# Normalize the data using MinMaxScaler
scaler = MinMaxScaler()
X_norm = scaler.fit_transform(X)

# Print the normalized data
print(X_norm)

[[0.02173913 0.         0.3212268  0.         1.         1.        ]
 [0.         1.         0.47914985 0.2        0.         0.66666667]
 [0.2173913  1.         0.45843422 0.6        0.         0.66666667]
 ...
 [0.         0.         0.56201238 0.         0.         0.66666667]
 [0.06521739 0.         0.26472962 0.         0.         1.        ]
 [0.93478261 0.         0.35270379 0.         1.         0.33333333]]


In [68]:
from sklearn.model_selection import train_test_split
# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [82]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import MinMaxScaler
import joblib
from sklearn.ensemble import RandomForestClassifier


In [85]:
# Define classifiers
rf = RandomForestClassifier(n_estimators=100, random_state=42)
logistic= LogisticRegression(random_state=42)
decision=DecisionTreeClassifier(random_state=42)

In [86]:
# bin the target variable into 3 intervals
y_train_categorical = pd.cut(y_train, bins=3, labels=False)

# train the classifiers on the categorical target variable
rf.fit(X_train, y_train_categorical)
logistic.fit(X_train, y_train_categorical)
decision.fit(X_train, y_train_categorical)

C:\Users\BENJAMIN\AppData\Roaming\Python\Python311\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


DecisionTreeClassifier(random_state=42)

In [94]:
# Make predictions on testing set
rf_pred = rf.predict(X_test)
logistic_pred = logistic.predict(X_test)
decision_pred=decision.predict(X_test)


In [95]:
# Ensemble predictions
ensemble_pred = np.round((rf_pred + logistic_pred + decision_pred) / 3)

In [96]:
from sklearn.metrics import mean_squared_error

ensemble_mse = mean_squared_error(y_test, ensemble_pred)
print('Ensemble mean squared error:', ensemble_mse)

Ensemble mean squared error: 323410814.1057698


In [98]:
import joblib
# Save the trained model to a file
filename = 'insurance.sav'
joblib.dump(rf, filename)

['insurance.sav']

In [99]:
# Load the saved model from a file
filename = 'churn_model.sav'
rf = joblib.load(filename)

# Use the loaded model to make predictions
y_pred = rf.predict(X_test)

# Print the predictions
print(y_pred)

[0 0 1 0 1 0 0 0 0 0 0 0 0 2 2 2 0 2 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 1 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 0 1 1 1 0 0 0 0 0 1 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0
 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 2 1 0 0 0 0 0 1 0 0
 0 0 2 0 0 1 0 0 0 0 1 1 0 0 0 0 0 0 2 2 1 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0
 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 2 0 0 2 0]


In [100]:
from flask import Flask, jsonify, request
# Create a Flask app
app = Flask(__name__)

# Define a route for the API
@app.route('/predict', methods=['POST'])
def predict():
    # Get the features from the request
    features = request.json['features']
     # Convert the features to a DataFrame
    X = pd.DataFrame.from_dict(features)
     # Return the prediction as a JSON response
    response = {'prediction': y_pred.tolist()}
    return jsonify(response)
# Run the Flask app
if __name__ == '__main__':
    app.run(debug=True)
    

 * Serving Flask app '__main__'
 * Debug mode: on


 * Running on http://127.0.0.1:5000
Press CTRL+C to quit
 * Restarting with stat


SystemExit: 1

C:\Users\BENJAMIN\AppData\Roaming\Python\Python311\site-packages\IPython\core\interactiveshell.py:3450: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)
