In [80]:
import pandas as pd
import  numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model  import LinearRegression 

In [81]:
df=pd.read_csv("C:/Users/BENJAMIN/Downloads/insurance.csv")

In [82]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       1338 non-null   int64  
 1   sex       1338 non-null   object 
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64  
 4   smoker    1338 non-null   object 
 5   region    1338 non-null   object 
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB


In [83]:
df.head()

age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [84]:
columns=df.columns.values.tolist()
print(columns)

['age', 'sex', 'bmi', 'children', 'smoker', 'region', 'charges']


In [85]:
# Check for missing data
df.isnull().sum()

# Impute missing data with mean
df = df.fillna(df.mean())
print (df)

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]


C:\Users\BENJAMIN\AppData\Local\Temp\ipykernel_8932\883001002.py:5: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df = df.fillna(df.mean())


In [86]:
from sklearn.preprocessing import LabelEncoder
cat_cols = ["sex", "smoker", "region"]
# Create LabelEncoder object
le = LabelEncoder()
# Encode the categorical features
for col in cat_cols:
    df[col] = le.fit_transform(df[col])
# Print the encoded dataset
print(df)

      age  sex     bmi  children  smoker  region      charges
0      19    0  27.900         0       1       3  16884.92400
1      18    1  33.770         1       0       2   1725.55230
2      28    1  33.000         3       0       2   4449.46200
3      33    1  22.705         0       0       1  21984.47061
4      32    1  28.880         0       0       1   3866.85520
...   ...  ...     ...       ...     ...     ...          ...
1333   50    1  30.970         3       0       1  10600.54830
1334   18    0  31.920         0       0       0   2205.98080
1335   18    0  36.850         0       0       2   1629.83350
1336   21    0  25.800         0       0       3   2007.94500
1337   61    0  29.070         0       1       1  29141.36030

[1338 rows x 7 columns]


In [87]:
# Separate features and target
X = df.drop(['charges'], axis=1)
y = df['charges']

In [88]:
# Normalize the data using MinMaxScaler
scaler = MinMaxScaler()
X_norm = scaler.fit_transform(X)

# Print the normalized data
print(X_norm)

[[0.02173913 0.         0.3212268  0.         1.         1.        ]
 [0.         1.         0.47914985 0.2        0.         0.66666667]
 [0.2173913  1.         0.45843422 0.6        0.         0.66666667]
 ...
 [0.         0.         0.56201238 0.         0.         0.66666667]
 [0.06521739 0.         0.26472962 0.         0.         1.        ]
 [0.93478261 0.         0.35270379 0.         1.         0.33333333]]


In [89]:
# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [90]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import MinMaxScaler
import joblib
# Initialize random forest model
rf = RandomForestRegressor(n_estimators=100, random_state=42)

# Train model on training set
rf.fit(X_train, y_train)

# Make predictions on testing set
y_pred = rf.predict(X_test)
print(y_pred)

[11129.2098068   5279.3315315  28261.1135955  10712.5176533
 34526.7010364   9133.2200995   2099.488392   14442.4762686
  6038.4547952  10666.8380547  20235.6347478   7384.2326753
  4894.364618   46496.3565675  48415.4409348  45504.3021979
  9925.6052816  43438.6655569   9047.2776489  24237.7887065
  6187.8446445  10763.3418747   2281.7628236   2711.6813281
 12010.4130091  12186.2529167  13297.2574337   6933.1372034
 10370.8181676   5050.91832532  7689.3889535  11742.2911635
  2513.7029761   5445.6901702   3189.7811542  10587.6009703
  2671.0216105   8191.9397535  23487.365382   39321.461817
  6489.3096034   2746.9478863  11998.2359501  14479.734655
  5821.3102169  15350.0639343  15116.0722669   5903.1316494
 42330.6993162   7200.0425201  13889.2426335   2171.0700651
  6805.0877189   1831.43492725 12272.9471291  11834.6874174
  3792.47262    45082.2046762  12825.0184811  15119.4273718
 13736.0708405   7602.9680586  21049.165789    7779.025634
 12088.0951161   6473.9952209  18350.754487

In [92]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

# Calculate evaluation metrics
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)

# Print evaluation metrics
print("Mean Absolute Error:", mae)
print("Mean Squared Error:", mse)
print("Root Mean Squared Error:", rmse)

Mean Absolute Error: 2533.674643617756
Mean Squared Error: 21073365.415079337
Root Mean Squared Error: 4590.5735387944


In [71]:
from flask import Flask, jsonify, request
# Create a Flask app
app = Flask(__name__)

# Define a route for the API
@app.route('/predict', methods=['POST'])
def predict():
    # Get the features from the request
    features = request.json['features']
     # Convert the features to a DataFrame
    X = pd.DataFrame.from_dict(features)
     # Return the prediction as a JSON response
    response = {'prediction': y_pred.tolist()}
    return jsonify(response)
# Run the Flask app
if __name__ == '__main__':
    app.run(debug=True)
    ''

 * Serving Flask app '__main__'
 * Debug mode: on


 * Running on http://127.0.0.1:5000
Press CTRL+C to quit
 * Restarting with stat


SystemExit: 1

C:\Users\BENJAMIN\AppData\Roaming\Python\Python311\site-packages\IPython\core\interactiveshell.py:3450: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)
